# Generated by Django 3.1.7 on 2021-05-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakefilmsweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='distributor',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
    ]
