# Generated by Django 3.1.7 on 2021-05-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakefilmsweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='age',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='serie',
            old_name='age',
            new_name='year',
        ),
    ]
