# Generated by Django 3.1.7 on 2021-05-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakefilmsweb', '0002_auto_20210519_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='distributor',
            new_name='director',
        ),
    ]
