# Generated by Django 3.1.7 on 2021-04-05 08:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fakefilmsweb', '0004_auto_20210405_0828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSerieList',
            new_name='UsersMovieList',
        ),
        migrations.RenameModel(
            old_name='UserMovieList',
            new_name='UsersSerieList',
        ),
        migrations.RenameField(
            model_name='usersmovielist',
            old_name='serie',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='usersserielist',
            old_name='movie',
            new_name='serie',
        ),
        migrations.AlterUniqueTogether(
            name='usersmovielist',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='usersserielist',
            unique_together={('user', 'serie')},
        ),
    ]
