# Generated by Django 3.1.7 on 2021-04-05 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakefilmsweb', '0005_auto_20210405_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersserielist',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakefilmsweb.serie'),
        ),
    ]
